# Generated by Django 3.1.7 on 2021-03-10 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feeding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Feeding date')),
                ('meal', models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner')], default='Dinner', max_length=1)),
                ('mogwai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.mogwai')),
            ],
        ),
    ]
