# Generated by Django 3.1.7 on 2021-03-10 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210310_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mogwai',
            name='toys',
            field=models.ManyToManyField(blank=True, to='main_app.Toy'),
        ),
    ]
